apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: akj4hvt3d-go
  janus-idp.io/tekton: akj4hvt3d-go
  backstage.io/kubernetes-id: akj4hvt3d-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: akj4hvt3d-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
